name: CD

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed

jobs:
  meta-data:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: does it run?
        if: ${{ github.event.pull_request.type.unlabeled }}
        run: echo "it ran"
      - name: what label?
        run: echo "${{github.event.label.name}}"
      - name: echo type
        run: echo "${{ github.event_name}} ${{github.event.action}}"
      - name: Has label?
        run: echo "Has 'release:patch' label? ${{ contains(github.event.*.labels.*.name, 'release:patch') }}"
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Makes sure package.json is up to date
        uses: technote-space/package-version-check-action@v1
  prod-deploy:
    if: ${{ github.event.pull_request.merged == true }}
    uses: ./.github/workflows/prod-deploy.yml
    secrets: inherit