name: CD

on:
  pull_request:
    types:
      - closed

jobs:
  version:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: Patch?
      if: ${{ contains(github.event.*.labels.*.name, 'release:patch') }}
      run: npm version patch
    - name: Minor?
      if: ${{ contains(github.event.*.labels.*.name, 'release:minor') }}
      run: npm version minor
    - name: Major?
      if: ${{ contains(github.event.*.labels.*.name, 'release:major') }}
      run: npm version major
    - name: Get current npm version
      id: version
      run: |
        PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
        echo "TAG=${PACKAGE_VERSION}" >> $GITHUB_OUTPUT
    # This action creates a tag whether you want it to or not, so we will delete it in the next step,
    # because the release-on-push-action _also_ creates a tag
    - name: Push files and tag
      uses: Amraneze/push-to-protected-branch@main
      with:
        repository: ${{ github.repository }}
        branch_name: ${{ github.ref_name }}
        github_token: ${{ secrets.ACCESS_TOKEN }}
        commit_message: 'ci: build version ${{ steps.version.outputs.TAG }}'
        tag_version: ${{ steps.version.outputs.TAG }}
        create_tag: false
        files_to_commit: 'package.json'
    - name: Delete useless tag that push-to-protected-branch creates that I don't need
      run: git push origin :refs/tags/${{ steps.version.outputs.TAG }}
    - name: Do actual release
      uses: rymndhng/release-on-push-action@master
      with:
        bump_version_scheme: minor
        use_github_release_notes: true
