name: CI

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
      - closed
      - reopened

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: does it run?
        if: ${{ github.event.pull_request.type.unlabeled }}
        run: echo "it ran"
      - name: what label?
        run: echo "${{github.event.label.name}}"
      - name: echo type
        run: echo "${{ Object.keys(github.event.pull_request) }}"
