name: CI

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
      - reopened

jobs:
  check-labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          any_of: version-major,version-minor,version-patch,version-none
          repo_token: ${{ secrets.GITHUB_TOKEN }}
  dev-deploy:
    if: ${{ github.event.action != 'unlabeled' && github.event.pull_request.merged != true }}
    uses: ./.github/workflows/dev-deploy.yml
    with:
      docker_push: ${{ contains(github.event.*.labels.*.name, 'dev-deployment') }}
    secrets: inherit