name: CI

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
      - closed
      - reopened

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: echo type
        run: echo "${{ github.event.pull_request.type }}"
