name: CI

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
      - closed
      - reopened

jobs:
  test1:
    if: ${{ github.event.pull_request.type.unlabeled && github.event.label.name == 'dev-deployment' }}
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
