name: Dev Deployment

on:
  workflow_call:
    inputs:
      tag:
        description: "Tag to deploy (eg 1.0.0), defaults to latest"
        required: false
        type: string
      docker_push:
        description: "Push the docker image"
        required: false
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to deploy (eg 1.0.0), defaults to latest"
        required: false
      docker_push:
        description: "Push the docker image"
        required: false
        type: boolean
        default: true

jobs:
  meta-data:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: does it run?
        if: ${{ github.event.pull_request.type.unlabeled }}
        run: echo "it ran"
      - name: what label?
        run: echo "${{github.event.label.name}}"
      - name: echo type
        run: echo "${{ github.event_name}} ${{github.event.action}}"
      - name: Has label?
        run: echo "Has 'target' label? ${{ contains(github.event.*.labels.*.name, 'target') }}"
  validate:
    uses: ./.github/workflows/reusable_validate.yml
    secrets: inherit
  build:
    needs: validate
    uses: ./.github/workflows/reusable_build.yml
    with:
      tag: ${{ inputs.tag }}
      environment: ${{ inputs.environment }}
      docker_push: ${{ inputs.docker_push }}
    secrets: inherit
  dev-deploy:
    if: ${{ inputs.docker_push }}
    needs: build
    uses: ./.github/workflows/reusable_deploy.yml
    with:
      tag: ${{ inputs.tag }}
      environment: dev
    secrets: inherit
