name: Dev Deployment

on:
  workflow_call:
    inputs:
      tag:
        description: "Tag to deploy (eg 1.0.0), defaults to latest"
        required: false
        type: string
      docker_push:
        description: "Push the docker image"
        required: false
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to deploy (eg 1.0.0), defaults to latest"
        required: false
      docker_push:
        description: "Push the docker image"
        required: false
        type: boolean
        default: true

concurrency:
  group: dev-deploy-${{ github.ref }}-1
  cancel-in-progress: true


jobs:
  validate:
    uses: ./.github/workflows/reusable_validate.yml
    with:
      tag: ${{ inputs.tag }}
    secrets: inherit
  build:
    needs: validate
    uses: ./.github/workflows/reusable_build.yml
    with:
      tag: ${{ inputs.tag }}
      environment: ${{ inputs.environment }}
      docker_push: ${{ inputs.docker_push }}
    secrets: inherit
  dev-deploy:
    if: ${{ inputs.docker_push }}
    needs: build
    uses: ./.github/workflows/reusable_deploy.yml
    with:
      tag: ${{ inputs.tag }}
      environment: dev
    secrets: inherit
