name: CD

on:
  pull_request:
    types:
      - closed
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: "Version to Deploy"

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Makes sure package.json is up to date
        uses: technote-space/package-version-check-action@v1

  prod-deploy:
    uses: ./.github/workflows/prod-deploy.yml
    with:
      tag: ${{ inputs.tag }}
    secrets: inherit