name: Prod Deployment
on:
  workflow_call:
    inputs:
      tag:
        description: "Tag to deploy (eg 1.0.0), defaults to latest"
        required: false
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to deploy (eg 1.0.0), defaults to latest"
        required: false

jobs:
  meta-data:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: does it run?
        if: ${{ github.event.pull_request.type.unlabeled }}
        run: echo "it ran"
      - name: what label?
        run: echo "${{github.event.label.name}}"
      - name: echo type
        run: echo "${{ github.event_name}} ${{github.event.action}}"
      - name: Has label?
        run: echo "Has 'target' label? ${{ contains(github.event.*.labels.*.name, 'target') }}"
  version:
    runs-on: [self-hosted, tsa]
    steps:
      - name: Makes sure package.json is up to date
        uses: technote-space/package-version-check-action@v1
  stage-deploy:
    uses: ./.github/workflows/stage-deploy.yml
    with:
      tag: ${{ inputs.tag }}
    secrets: inherit
  prod-deploy:
    needs: stage-deploy
    uses: ./.github/workflows/reusable_deploy.yml
    with:
      tag: ${{ inputs.tag }}
      environment: prod
    secrets: inherit
