name: Prod Deployment
on:
  workflow_call:
    inputs:
      tag:
        description: "Tag to deploy (eg 1.0.0), defaults to latest"
        required: false
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to deploy (eg 1.0.0), defaults to latest"
        required: false

concurrency:
  group: prod-deploy-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Makes sure package.json is up to date
        uses: technote-space/package-version-check-action@v1
  stage-deploy:
    uses: ./.github/workflows/stage-deploy.yml
    with:
      tag: ${{ inputs.tag }}
    secrets: inherit
  prod-deploy:
    needs: stage-deploy
    uses: ./.github/workflows/reusable_deploy.yml
    with:
      tag: ${{ inputs.tag }}
      environment: prod
    secrets: inherit
