name: Release

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: "Version to Deploy"

jobs:
  prod-deploy:
    uses: ./.github/workflows/prod-deploy.yml
    with:
      tag: ${{ inputs.tag }}
    secrets: inherit