name: Deploy

on:
  workflow_call:
    inputs:
      tag:
        description: "Tag to deploy (eg 1.0.0), defaults to latest"
        required: false
        type: string
      environment:
        description: "Environment to deploy to (dev|stage|prod)"
        required: true
        type: string

jobs:
  reusable_deploy:
    name: ${{ inputs.environment }} deploy
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "#### Deploying App" >> $GITHUB_STEP_SUMMARY
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo "Checkout run" >> $GITHUB_STEP_SUMMARY
      - name: Get Tag or SHA
        id: tag
        uses: tenhaus/get-release-or-tag@v2
      - run: echo "Got tag ${{ inputs.tag || steps.tag.outputs.tag }}" >> $GITHUB_STEP_SUMMARY
      - name: Deploy app to Harness
        run: |
          echo "DEPLOY USING HARNESS"
          echo "Deployed app:${{ inputs.tag || steps.tag.outputs.tag }} to ${{ inputs.environment }} using Harness" >> $GITHUB_STEP_SUMMARY
