name: Validate

on:
  workflow_call:

jobs:
  code-validation:
    name: Check Format, Lint and Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - name: Install dependencies
        run: yarn
      - name: Check Format
        run: yarn test:format
      - name: Lint
        run: yarn test:lint
      - name: Unit Test
        run: yarn test:unit
