name: Validate

on:
  workflow_call:

jobs:
  meta-data:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: does it run?
        if: ${{ github.event.pull_request.type.unlabeled }}
        run: echo "it ran"
      - name: what label?
        run: echo "${{github.event.label.name}}"
      - name: echo type
        run: echo "${{ github.event_name}} ${{github.event.action}}"
      - name: Has label?
        run: echo "Has 'target' label? ${{ contains(github.event.*.labels.*.name, 'target') }}"
  code-validation:
    name: Check Format, Lint and Tests
    runs-on: [self-hosted, tsa]
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN_GITHUB }}

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2

      - name: Install dependencies
        run: yarn

      - name: Check Format
        run: yarn test:format

      - name: Lint
        run: yarn test:lint

      - name: Unit Test
        run: yarn test:unit
