name: Stage Deployment
on:
  workflow_call:
    inputs:
      tag:
        description: "Tag to deploy (eg 1.0.0), defaults to latest"
        required: false
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to deploy (eg 1.0.0), defaults to latest"
        required: false

concurrency:
  group: stage-deploy-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/reusable_validate.yml
    secrets: inherit
  build:
    needs: validate
    uses: ./.github/workflows/reusable_build.yml
    with:
      tag: ${{ inputs.tag }}
      environment: ${{ inputs.environment }}
    secrets: inherit
  stage-deploy:
    needs: build
    uses: ./.github/workflows/reusable_deploy.yml
    with:
      tag: ${{ inputs.tag }}
      environment: stage
    secrets: inherit
